[package]
name = "cmdirstat"
version = "26.6.4"
edition = "2021"

[dependencies]
ratatui = "0.26"
crossterm = "0.27"
jwalk = "0.8"
human_bytes = "0.4"
anyhow = "1.0"
clap = { version = "4.4", features = ["derive"] }
rayon = "1.8"
unicode-width = "0.1"
chrono = { version = "0.4", default-features = false, features = ["clock", "std"] }

[target.'cfg(windows)'.dependencies]
windows-sys = { version = "0.52", features = ["Win32_Storage_FileSystem", "Win32_System_IO", "Win32_Foundation", "Win32_Security"] }
